tap "anomalyco/tap"
tap "gromgit/brewtils"
tap "jandedobbeleer/oh-my-posh"
tap "run-llama/liteparse"
tap "shopify/shopify"
tap "smudge/smudge"
tap "steipete/tap"
tap "typesense/tap", trusted: true
tap "typewhisper/tap"
tap "westpoint-io/dustoff"
tap "xykong/tap"
brew "agent-browser"
brew "anomalyco/tap/opencode", trusted: true
brew "aom"
brew "caddy", restart_service: :changed
brew "cloudflared"
brew "doctl"
brew "dust"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fontconfig"
brew "freetds"
brew "freetype"
brew "fzf"
brew "gd"
brew "gdal"
brew "gh"
brew "gifsicle"
brew "git"
brew "glib"
brew "glow"
brew "gnutls"
brew "googleworkspace-cli"
brew "gromgit/brewtils/taproom"
brew "harfbuzz"
brew "httpd"
brew "imagemagick"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jpeg-xl"
brew "jq"
brew "lazygit"
brew "leptonica"
brew "libass"
brew "libgit2"
brew "libpng"
brew "libssh2"
brew "libtiff"
brew "llmfit"
brew "mas"
brew "neovim"
brew "nghttp2"
brew "nginx"
brew "oh-my-posh"
brew "openjpeg"
brew "p11-kit"
brew "php", restart_service: :changed
brew "php@8.4"
brew "playwright-cli"
brew "poppler"
brew "rclone"
brew "redis", restart_service: :changed
brew "resvg"
brew "ripgrep"
brew "run-llama/liteparse/llamaindex-liteparse", trusted: true
brew "rust"
brew "s3cmd"
brew "shopify/shopify/shopify-cli", trusted: true
brew "smudge/smudge/nightlight", trusted: true
brew "stow"
brew "tesseract"
brew "tmux"
brew "typesense/tap/typesense-server@30.2"
brew "unbound"
brew "uv"
brew "watchman"
brew "webp"
brew "westpoint-io/dustoff/dustoff", trusted: true
brew "worktrunk"
brew "wp-cli"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh"
cask "1password-cli"
cask "android-platform-tools"
cask "bloom"
cask "bruno"
cask "codex"
cask "dockdoor"
cask "figma"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"
cask "gcloud-cli"
cask "ghostty"
cask "iina"
cask "jordanbaird-ice"
cask "losslesscut"
cask "mitmproxy"
cask "mos"
cask "ngrok"
cask "numi"
cask "obs"
cask "obsidian"
cask "openmtp"
cask "pearcleaner"
cask "phpstorm"
cask "rustdesk"
cask "steipete/tap/codexbar", trusted: true
cask "tableplus"
cask "telegram"
cask "ticktick"
cask "typewhisper/tap/typewhisper", trusted: true
cask "xykong/tap/flux-markdown", trusted: true
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Discrete", id: 6746067740
mas "Dropover", id: 1355679052
mas "Folder Preview", id: 6698876601
mas "RasterFox", id: 6749489566
mas "Slack", id: 803453959
mas "Spark Desktop", id: 6445813049
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
npm "corepack"
uv "graphifyy"
